platform :ios, '8.0'
target ‘sixty_seconds’ do 
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'react-native-fetch-blob',:path => '../node_modules/react-native-fetch-blob'
  pod 'PLPlayerKit'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
     'DevSupport',
     'RCTText',
     'RCTNetwork',
     'RCTWebSocket',
     'BatchedBridge',]
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
 
end
